import Container from '@/Components/Container'
import CreateGroupForm from '@/Components/CreateGroupForm'
import CreateTodoForm from '@/Components/CreateTodoForm'
import Header from '@/Components/Header'
import TodoList from '@/Components/TodoList'
import { RootState } from '@/store/store'
import { useAppSelector } from '@/store/storeHooks'
import { Section } from '@/types/types'
import Head from 'next/head'



export default function Home() {

  const sections = useAppSelector((e) => e.user?.sections as Section[])
  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Header/>

    <Container>
      {JSON.stringify(sections)}
      <CreateGroupForm/>
    </Container>

    
    </>
  )
}