import Header from "@/Components/Header"
import Calendar from "@/Components/calendar/Calendar"
import TabsManage from "@/Components/manageTodo/TabsManage"
import { updateTodoDate } from "@/store/async/async"
import { useAppDispatch, useAppSelector } from "@/store/storeHooks"
import { Container, Flex, Tab, TabList, TabPanel, TabPanels, Tabs } from "@chakra-ui/react"
import Head from "next/head"
import { useState } from "react"

export default function Home() {
  const todos =  useAppSelector(e => e.user?.todos)
  const dispatch = useAppDispatch()

  if (!todos) return 

  return (
    <>
      <Head>
        <title>Главная</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
 
      <Container maxW={'1280px'} display="flex" flexDirection="column" gap="30px">
        <Tabs>
            <TabList >
                <Tab>
                    Статистика
                </Tab>
                <Tab>
                    Календарь
                </Tab>
                <Tab>
                    Назначение
                </Tab>
            </TabList>


            <TabPanels>
                <TabPanel>
                <p>one!</p>
                </TabPanel>
                <TabPanel>
              <Calendar onChangeDate={(idTodo, date) => {
                  dispatch(updateTodoDate({
                    date: date,
                    todoId: idTodo
                  }))
              }} items={todos.filter(todo => todo.dateEnded)}/>
                </TabPanel>
                <TabPanel>
                <p>three!</p>
                </TabPanel>
            </TabPanels>
          
          </Tabs>


      </Container>
    </>
  )
}